<!-- Header of GISA website -->
<?php include("header.php"); ?>
<script>
	document.getElementById("a_welcome").className += " highlight";
</script>


<!-- Main page content follows the header -->
<div id="page-content" style="line-height: 1.5em">
<h3>The University at Buffalo: An Historic Overview</h3>
<p class="question">1846-1900
<p>The University of Buffalo was incorporated by an act of the New York State Legislature on May 11, 1846.
Originally chartered to establish "academic, theological, legal and medical departments," it developed initially as a medical school with Millard Fillmore as its first chancellor. The school began operations in a leased building at the corner of Seneca and Washington Streets on February 25, 1847, with 72 students and a faculty of seven physicians. UB constructed its first building, a two and one-half story brownstone structure, at Main and Virginia Streets in 1849. At the dedication, Fillmore called for the university to fulfill its original promise and to establish academic branches and a department of law.

<p>Expansion in the spirit Fillmore envisioned eventually gained impetus in the late 1880s and early 1890s, under the chancellorship of E. Carlton Sprague. The School of Pharmacy was organized as the second division of the university in 1886. An independently established Law School, begun in 1887, was incorporated into the university in 1891, and in 1892 the School of Dentistry was opened. In 1893, the medical school moved to a building on High Street.

<p class="question">1900-1920
<p>Attorney Charles P. Norton, a native Buffalonian who helped found the law school, became UB's acting chancellor in 1905 and chancellor in 1908. During Norton's tenure, UB bought the 150-acre Buffalo Plains site on north Main Street, later to become the university's home. Norton bequeathed his entire estate to the university, providing funds for a student-union building and for the endowment of UB's highest award, the Chancellor's Medal, presented annually since 1925 to an outstanding citizen of Buffalo. The university's first liberal-arts curriculum was developed when the American Medical Association required at least one preliminary year of liberal-arts work as part of physician education. The courses were instituted in 1913 and were awarded departmental status in 1915. That same year, the Women's Educational and Industrial Union of Buffalo offered its building on Niagara Square as the home for the new, full-scale arts college, if the university could raise a $100,000 endowment within a year. This challenge was met through a $250,000 contribution from Mrs. Seymour H. Knox and her family in honor of her late husband. The College of Arts and Sciences, authorized by the State Department of Education in 1919, had 600 students and 31 full- and part-time faculty within one year.

<p class="question">1920 - 1950
<p>By 1920, the university was no longer able to sustain itself entirely by student fees, occasional emergency donations or contributions for the construction of a new building. Recognizing this, Walter P. Cooke, chair of the UB Council, acting chancellor after Norton's retirement and director of the Liberty Loan Drives of World War I, led the university's first city-wide financial campaign. The fund campaign of 1920 made it possible to begin developing the Buffalo Plains property and to buy additional acreage from private owners to comprise the 178 acres of the present Main Street Campus.For the next 28 years, UB advanced under the leadership of Dr. Samuel Paul Capen, founder and director of the American Council on Education and Woodrow Wilson's advisor on higher education. Capen helped form the loose amalgam of independent schools into a cohesive institution, added more full-time faculty, developed the physical plant and the curriculum, and, in 1922, introduced graduate work to the arts and sciences college. During Capen's tenure, the university established several other divisions -- the School of Business Administration (now Management, 1923), an evening division (now Millard Fillmore College, 1923), the School of Education (1931) and the School of Social Work (1936). The Graduate School of Arts and Sciences (now simply the Graduate School) offered its first programs as an individual division in 1939. The program in nursing became a separate unit of the School of Medicine in 1940. The end of World War II brought a deluge of students on the G.I. Bill who increased UB enrollment by 400 percent and doubled the total population of the institution. The School of Engineering, now the School of Engineering and Applied Sciences, was established in 1946 in response to a newly emerging professional need.

<p class="question">1950 - 1962
<p>The UB Council voted in 1950 to build a medical-dental complex on the Main Street Campus, which was dedicated as Capen Hall in 1953. Millard Fillmore College and the last of the administrative offices moved to the central campus by 1955, bringing about the consolidation of all facilities except the School of Law. Dr. T. Raymond McConnell, who served as chancellor from 1950-54, presided over the opening of the university's first residence halls. Clifford Furnas, chancellor from 1954-62 and president from 1962-66, led the university through an extensive program of enrichment and building. Major construction projects included an $8 million health-sciences complex; the 11-story Tower residence hall for men, the 10-story Ella Conger Goodyear Hall for women, Acheson Hall of Chemistry, Squire Hall and the Charles H. Diefendorf classroom building. The Albright Art School merged with the UB Department of Art in 1957.

<p class="question">1962-1980
<p>Sponsored research expenditures grew tenfold during the 1950s and reached $4.2 million by 1962. From 1960-62, Furnas presided over the integration of UB into the state university system as the State University of New York at Buffalo, one of four university centers in the system and its largest and most comprehensive campus. By 1962, the total area of the university buildings was 2,049,136 square feet in 43 buildings, up from 769,160 square feet in 1952. Enrollment totaled 10,881 full- and part-time day students, an increase of more than 100 percent over 1952. In 1964, plans were announced to construct a new, $130 million campus three miles north of Main Street in Amherst, and to convert the Main Street Campus to a health-sciences center. Plans for the new campus were held up, however, and in the meantime 12 "temporary" buildings were erected on the Main Street Campus and an "interim" campus -- the Ridge Lea Campus -- was leased by the university. Martin Meyerson, who succeeded Furnas as UB president in 1966, reorganized UB academically into seven faculties and developed a college system that established 30 undergraduate academic units, each consisting of no more than 1,000 students. The School of Information and Library Studies and School of Health Related Professions opened in 1966. Three years later, the School of Architecture and Environmental Design (now School of Architecture and Planning) opened its doors. Student protests against the Vietnam War during the late 1960s disrupted life on campus and in the Buffalo community. Robert Ketter, who assumed the UB presidency in 1970, helped reestablish harmonious relations with the Buffalo community at a time when UB enjoyed a growing national academic reputation. Construction of the vast new Amherst Campus began in June 1970. By the following March, plans were already being scaled down. The project ultimately was revised to accommodate 25,000 students instead of the 40,000 for which it was originally planned. The first buildings to go up were the Governors Complex residential hall and John Lord O'Brian Hall (home of the School of Law), both of which opened in 1973.

<p>Financial problems fueled by rampant inflation caused further construction delays and for several more years students, faculty and administrators commuted between Main Street, Ridge Lea and the embryonic new campus. By 1976, however, 10,000 students were using the new campus and in 1977-78, with the completion of the massive Capen/Norton/Talbert Hall complex, Amherst officially became the central campus.

<p class="question">1980 -1995
<p>By 1980, 31 buildings had been completed, were underway or ready to be let for contract on the Amherst campus. Important centers of research also were established there. Steven B. Sample took office as UB's 12th chief executive in 1982, when Ketter relinquished his position to return to the School of Engineering faculty. Sample made significant changes in administrative reporting systems, fostered an increase in external research funding and established an undergraduate college as the focus for a new and distinctive curriculum. A new student activity center opened in the early 1980s, along with the second phase of the mammoth recreation and athletics complex. Commercial development of the area adjacent to Lake LaSalle began.

<p>In 1986, UB was awarded $25 million from the National Science Foundation to establish the National Center for Earthquake Engineering Research, initially headed by former UB President Robert Ketter. The NSF awarded the center a five-year, $21 million renewal grant in 1991. In 1989, UB was elected to membership in the Association of American Universities, becoming the first and still only public research university in New York and New England invited to join the most prestigious and exclusive academic organization in the country. With the election of UB and Rutgers University, the organization had only 56 members. William R. Greiner, who joined the faculty of the UB School of Law in 1967 and who in 1984 was appointed UB's first university provost, was appointed UB's 13th president in September 1991. One of his first actions was to underscore UB's commitment to the community by the creation at the vice-president level of an Office of Public Service and Urban Affairs, a first for a U.S. university. The opening of a new Student Union on the Amherst Campus in 1992 was followed two years later by the opening of the Center for the Arts and the Natural Sciences and Mathematics Complex. In 1995, UB enrolls 25,000 students, offers almost 300 degree programs at the baccalaureate, master's, doctoral and first professional level and has an operating budget of almost $600 million, with some 4,500 associated full-time positions. It is one of Western New York's leading employers.

<p>UB now spends more than $122 million in external funds annually on research. In 1994, the total of contract and grant awards from external sponsors -- which in some cases represented funds to be expended over several years -- was $284 million. Industrial support of UB research in 1994 reached a record $19 million. The university pumps $1.41 billion a year into the Western New York economy. Its annual direct expenditures total $582 million, with $495 million of that amount spent in Western New York. For each $1 spent, more than $1.40 in additional activity is generated in the Western New York economy, according to a report prepared by the UB Center for Regional Studies.

<p>In the first four years of his presidency, Professor Greiner has focused the university community on fulfilling its mission of education, research and public service as it approaches a new century. UB has taken a leadership position in preserving the quality and accessibility of public undergraduate, graduate and professional education in the face of shrinking state funding.

<p class="question">Prepared by UB News Services, October 1995</p>

<p class="big"><a style="float: left;" href="javascript:history.back()">&lt;&lt; Back</a> <a style="float: right;" href="#">Top  &gt;&gt;</a></p>
</div>


<!-- Then comes the spider.. I mean the "sidebar" -->


<!-- And the footer wraps it all -->
<?php include("footer.php"); ?>
	